version: '3.8'

services:
  mysql_database:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: assignment_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  pyserver2:
    build: ./pyserver2
    container_name: pyserver2
    depends_on:
      - mysql_database
    ports:
      - "5000:5000"

  pyclient2:
    build: ./pyclient2
    container_name: pyclient2
    depends_on:
      - pyserver2

  cserver1:
    build: ./cserver1
    container_name: cserver1
    depends_on:
      - mysql_database
    ports:
      - "8080:8080"

  cclient2:
    build: ./cclient2
    container_name: cclient2
    depends_on:
      - cserver1
